version: '2.0'
services:
  customerorderservice:
    image: customerorderservice:1.1.1
    build: ./customerorderservice
    ports:
      - "8080:8080"
    environment:
      - CUSTOMER_SVC=customerservice
      - ORDER_SVC=orderservice
  orderservice:
    image: orderservice:1.1.0
    build: ./orderservice
    ports:
      - "9000:8080"
  customerservice:
    image: customerservice:1.1.0
    build: ./customerservice
    ports:
      - "9010:8080"
