---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyVpcCIDR:
    Description: CIDR block for VPC defaults to 10.45.0.0
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}'
    ConstraintDescription: Must be an IP address in the form x.x.x.x
    Type: String
    Default: 10.45.0.0

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Join [ '', [!Ref MyVpcCIDR, '/16']]
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName

  IPv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      VpcId: !Ref VPC
      AmazonProvidedIpv6CidrBlock: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn:
      - IPv6CidrBlock
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs 
          Ref: 'AWS::Region'
      VpcId: !Ref VPC
      CidrBlock: !Select [0, !Cidr [ !Join [ '', [!Ref MyVpcCIDR, '/16']], 16, 12]]
      Ipv6CidrBlock: !Select [ 1, !Cidr [ !Select [ 0, !GetAtt [ VPC, Ipv6CidrBlocks ]], 256, 64 ]]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref AWS::StackName
              - '-subnet-public1'
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn:
      - IPv6CidrBlock
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs 
          Ref: 'AWS::Region'
      VpcId: !Ref VPC
      CidrBlock: !Select [1, !Cidr [ !Join [ '', [!Ref MyVpcCIDR, '/16']], 16, 12]]
      Ipv6CidrBlock: !Select [ 2, !Cidr [ !Select [0, !GetAtt [ VPC, Ipv6CidrBlocks ]], 256, 64 ]]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref AWS::StackName
              - '-subnet-public2'  
    
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs 
          Ref: 'AWS::Region'
      VpcId: !Ref VPC
      CidrBlock: !Select [8, !Cidr [ !Join [ '', [!Ref MyVpcCIDR, '/16']], 16, 12]]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref AWS::StackName
              - '-subnet-private'

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: PrivateRouteTbl
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId:
        Fn::GetAtt:
        - EIP
        - AllocationId
      SubnetId: !Ref PublicSubnet1

  EIP:
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::EIP
    Properties:
        Domain: vpc
  Route:
    Type: AWS::EC2::Route
    Properties:
        RouteTableId:
          Ref: PrivateRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NatGateway

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${AWS::StackName}-ecs"
      GroupDescription: Allows traffic on port 8080 into the ECS container VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: !Join [ ":", [ !Ref "AWS::StackName", ECSSecurityGroup ] ]
      VpcId: !Ref VPC

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${AWS::StackName}-alb"
      GroupDescription: Allows traffic from the Internet via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: !Join [ ":", [ !Ref "AWS::StackName", ALBSecurityGroup ] ]
      VpcId: !Ref VPC

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: dualstack
      Name: !Sub "${AWS::StackName}-alb"
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}-alb"
      Type: application

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: !Sub "${AWS::StackName}-tg"
      TargetType: ip
      Protocol: HTTP
      Port: 8080
      VpcId: !Ref VPC

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup    
      LoadBalancerArn: !Ref ALB
      Protocol: HTTP
      Port: 80

  MyServiceDiscovery:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties: 
      Description: Microservice discovery service
      Name: !Ref AWS::StackName
      Vpc: !Ref VPC
  
  MyECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

Outputs:
  VPC:
    Description: VPC ID for the ECS service
    Value: !Ref VPC
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", VpcID ] ]
  PublicSubnet1CIDR:
    Description: CIDR block of the public subnet
    Value: !Ref PublicSubnet1
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", PublicSubnet1 ] ]
  PublicSubnet2CIDR:
    Description: CIDR block of the public subnet
    Value: !Ref PublicSubnet2
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", PublicSubnet2 ] ]
  PrivateSubnetCIDR:
    Description: CIDR block of the private subnet
    Value: !Ref PrivateSubnet
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", PrivateSubnet ] ]
  SecurityGroupName:
    Description: Security group name
    Value: !Ref ECSSecurityGroup
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SecurityGroupName ] ]
  ECSClusterName:
    Description: ECS Cluster name
    Value: !Ref MyECSCluster
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", ECSClusterName ] ]
  MyServiceDiscovery:
    Description: Service Discovery name
    Value: !Ref MyServiceDiscovery
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", ServiceDiscoveryName ] ]
  TargetGroupName:
    Description: ALB Target Group name
    Value: !Ref ALBTargetGroup
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", ALBTargetGroupName ] ]