---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MyBase:
    Description: Previously supplied stack name for base infrastructure
    Type: String

Resources:
  CustomerServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the customer service
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: customer-service
      NamespaceId:
          Fn::ImportValue: !Sub "${MyBase}:ServiceDiscoveryName"
  
  MyCustomerService:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref MyBase
      DesiredCount: 1
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub "${MyBase}:SecurityGroupName"
          Subnets:
            - Fn::ImportValue: !Sub "${MyBase}:PrivateSubnet"
      SchedulingStrategy: REPLICA
      ServiceName: customer-service
      ServiceRegistries: 
        - RegistryArn: !GetAtt CustomerServiceDiscoveryService.Arn
      TaskDefinition: mystore-customer-service-td:3

  OrderServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the customer service
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: order-service
      NamespaceId:
          Fn::ImportValue: !Sub "${MyBase}:ServiceDiscoveryName"
  
  MyOrderService:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref MyBase
      DesiredCount: 1
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub "${MyBase}:SecurityGroupName"
          Subnets:
            - Fn::ImportValue: !Sub "${MyBase}:PrivateSubnet"
      SchedulingStrategy: REPLICA
      ServiceName: order-service
      ServiceRegistries: 
        - RegistryArn: !GetAtt OrderServiceDiscoveryService.Arn
      TaskDefinition: mystore-order-service-td:4
  
  CustomerOrderTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: !Sub "${AWS::StackName}-tg"
      TargetType: ip
      Protocol: HTTP
      Port: 8080
      VpcId: 
        Fn::ImportValue: !Sub "${MyBase}:VpcID"
      HealthCheckPath: /customerorders/status

  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: 
        Fn::ImportValue: !Sub "${MyBase}:ALBListener"
      Conditions:
      - Field: path-pattern
        PathPatternConfig:
          Values: 
            - /customerorders/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref CustomerOrderTargetGroup
      Priority: 1

  CustomerOrderServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the public facing customer order service
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: customerorder-service
      NamespaceId:
          Fn::ImportValue: !Sub "${MyBase}:ServiceDiscoveryName"

  MyCustomerOrderService:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref MyBase
      DesiredCount: 2
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub "${MyBase}:SecurityGroupName"
          Subnets:
            - Fn::ImportValue: !Sub "${MyBase}:PublicSubnet1"
            - Fn::ImportValue: !Sub "${MyBase}:PublicSubnet2"
      SchedulingStrategy: REPLICA
      ServiceName: customerorder-service
      TaskDefinition: mystore-customerorder-service-td:8
      LoadBalancers:
      - TargetGroupArn: !Ref CustomerOrderTargetGroup
        ContainerName: customerorder-service
        ContainerPort: 8080