---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MyBase:
    Description: Previously supplied stack name for base infrastructure
    Type: String

Resources:
  CustomerServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      ExecutionRoleArn:
        Fn::ImportValue: !Sub "${MyBase}:ECSExecutionRole"
      Family: !Sub ${AWS::StackName}-customer-service
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: 
        Fn::ImportValue: !Sub "${MyBase}:ECSExecutionRole"
      ContainerDefinitions:
        - Name: customer-service
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/customerservice:latest
          PortMappings:
            - ContainerPort: 8080
              Protocol: http
          Essential: true
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: /ecs/mystore-customers
                awslogs-region: ap-southeast-2
                awslogs-stream-prefix: ecs
                awslogs-create-group: true
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -s http://localhost:8080/customers/status | grep -q OK
            Interval: 60
            Retries: 3
            StartPeriod: 10
            Timeout: 2

  CustomerServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the customer service
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: customer-service
      NamespaceId:
          Fn::ImportValue: !Sub "${MyBase}:ServiceDiscoveryName"
  
  MyCustomerService:
    Type: AWS::ECS::Service
    DependsOn: CustomerServiceTaskDefinition
    Properties: 
      Cluster: !Ref MyBase
      DesiredCount: 1
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub "${MyBase}:SecurityGroupName"
          Subnets:
            - Fn::ImportValue: !Sub "${MyBase}:PrivateSubnet"
      SchedulingStrategy: REPLICA
      ServiceName: customer-service
      ServiceRegistries: 
        - RegistryArn: !GetAtt CustomerServiceDiscoveryService.Arn
      TaskDefinition: !Ref CustomerServiceTaskDefinition

  OrderServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      ExecutionRoleArn:
        Fn::ImportValue: !Sub "${MyBase}:ECSExecutionRole"
      Family: !Sub ${AWS::StackName}-order-service
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: 
        Fn::ImportValue: !Sub "${MyBase}:ECSExecutionRole"
      ContainerDefinitions:
        - Name: order-service
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/orderservice:latest
          PortMappings:
            - ContainerPort: 8080
              Protocol: http
          Essential: true
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: /ecs/mystore-orders
                awslogs-region: ap-southeast-2
                awslogs-stream-prefix: ecs
                awslogs-create-group: true
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -s http://localhost:8080/orders/status | grep -q OK
            Interval: 60
            Retries: 3
            StartPeriod: 10
            Timeout: 2

  OrderServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the customer service
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: order-service
      NamespaceId:
          Fn::ImportValue: !Sub "${MyBase}:ServiceDiscoveryName"
  
  MyOrderService:
    Type: AWS::ECS::Service
    DependsOn: OrderServiceTaskDefinition
    Properties: 
      Cluster: !Ref MyBase
      DesiredCount: 1
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub "${MyBase}:SecurityGroupName"
          Subnets:
            - Fn::ImportValue: !Sub "${MyBase}:PrivateSubnet"
      SchedulingStrategy: REPLICA
      ServiceName: order-service
      ServiceRegistries: 
        - RegistryArn: !GetAtt OrderServiceDiscoveryService.Arn
      TaskDefinition: !Ref OrderServiceTaskDefinition
  
  CustomerOrderTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: !Sub "${AWS::StackName}-tg"
      TargetType: ip
      Protocol: HTTP
      Port: 8080
      VpcId: 
        Fn::ImportValue: !Sub "${MyBase}:VpcID"
      HealthCheckPath: /customerorders/status

  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: 
        Fn::ImportValue: !Sub "${MyBase}:ALBListener"
      Conditions:
      - Field: path-pattern
        PathPatternConfig:
          Values: 
            - /customerorders/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref CustomerOrderTargetGroup
      Priority: 1

  CustomerOrderServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      ExecutionRoleArn:
        Fn::ImportValue: !Sub "${MyBase}:ECSExecutionRole"
      Family: !Sub ${AWS::StackName}-customerorder-service
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: 
        Fn::ImportValue: !Sub "${MyBase}:ECSExecutionRole"
      ContainerDefinitions:
        - Name: customerorder-service
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/customerorderservice:latest
          PortMappings:
            - ContainerPort: 8080
              Protocol: http
          Essential: true
          Environment:
            - Name: CUSTOMER_SVC
              Value: customer-service.mystore
            - Name: CUSTOMER_SVC_PORT
              Value: 8080
            - Name: ORDER_SVC
              Value: order-service.mystore
            - Name: ORDER_SVC_PORT
              Value: 8080
          LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: /ecs/mystore-customerorders
                awslogs-region: ap-southeast-2
                awslogs-stream-prefix: ecs
                awslogs-create-group: true
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -s http://localhost:8080/customerorders/status | grep -q OK
            Interval: 60
            Retries: 3
            StartPeriod: 10
            Timeout: 2

  CustomerOrderServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the public facing customer order service
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: customerorder-service
      NamespaceId:
          Fn::ImportValue: !Sub "${MyBase}:ServiceDiscoveryName"

  MyCustomerOrderService:
    Type: AWS::ECS::Service
    DependsOn: CustomerOrderServiceTaskDefinition
    Properties: 
      Cluster: !Ref MyBase
      DesiredCount: 2
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub "${MyBase}:SecurityGroupName"
          Subnets:
            - Fn::ImportValue: !Sub "${MyBase}:PublicSubnet1"
            - Fn::ImportValue: !Sub "${MyBase}:PublicSubnet2"
      SchedulingStrategy: REPLICA
      ServiceName: customerorder-service
      TaskDefinition: !Ref CustomerOrderServiceTaskDefinition
      LoadBalancers:
      - TargetGroupArn: !Ref CustomerOrderTargetGroup
        ContainerName: customerorder-service
        ContainerPort: 8080