---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MyBase:
    Description: Previously supplied stack name for base infrastructure
    Type: String

Resources:
  CustomerServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the customer service
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: customer-service
      NamespaceId:
          Fn::ImportValue: !Sub "${MyBase}:ServiceDiscoveryName"
  
  MyCustomerService:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref MyBase
      DesiredCount: 1
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub "${MyBase}:SecurityGroupName"
          Subnets:
            - Fn::ImportValue: !Sub "${MyBase}:PrivateSubnet"
      SchedulingStrategy: REPLICA
      ServiceName: customer-service
      ServiceRegistries: 
        - RegistryArn: !GetAtt CustomerServiceDiscoveryService.Arn
      TaskDefinition: mystore-customer-service-td:1

  OrderServiceDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties: 
      Description: Discovery Service for the customer service
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
      HealthCheckCustomConfig: 
        FailureThreshold: 1
      Name: order-service
      NamespaceId:
          Fn::ImportValue: !Sub "${MyBase}:ServiceDiscoveryName"
  
  MyOrderService:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref MyBase
      DesiredCount: 1
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub "${MyBase}:SecurityGroupName"
          Subnets:
            - Fn::ImportValue: !Sub "${MyBase}:PrivateSubnet"
      SchedulingStrategy: REPLICA
      ServiceName: order-service
      ServiceRegistries: 
        - RegistryArn: !GetAtt OrderServiceDiscoveryService.Arn
      TaskDefinition: mystore-order-service-td:1
  
  MyCustomerOrderService:
    Type: AWS::ECS::Service
    Properties: 
      Cluster: !Ref MyBase
      DesiredCount: 2
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub "${MyBase}:SecurityGroupName"
          Subnets:
            - Fn::ImportValue: !Sub "${MyBase}:PublicSubnet1"
            - Fn::ImportValue: !Sub "${MyBase}:PublicSubnet2"
      SchedulingStrategy: REPLICA
      ServiceName: customerorder-service
      TaskDefinition: mystore-customerorder-service-td:4